.pragma library

var animationRate = 100 // Changes how fast blocks fall
var animationEasy = animationRate
var animationMedium = animationRate - 10
var animationHard = animationRate - 50
var animationSuper = animationRate - 60
var blockNameEasy = "EasyBlock"
var blockNameMedium = "MediumBlock"
var blockNameHard = "HardBlock"
var blockNameEvil = "EvilBlock"
var blocks = [blockNameEasy, blockNameMedium, blockNameHard, blockNameEvil]
var collisionInterval = 50
var intervalEasy = 1500
var intervalMedium = 1200
var intervalHard = 800
var intervalSuper = 500
var interval = intervalEasy
var livesDefault = 3
var livesEasy = 5
var livesInfinite = -1
var pointsEasy = 100
var pointsMedium = 500
var pointsHard = 1000
var pointsEvil = -500
var settingsLivesDefault = 0
var settingsLivesEasy = 1
var settingsLivesInfinite = 2
var speed = 10
var speedEasy = speed
var speedMedium = speed * 2
var speedHard = speed * 3
var speedEvil = speed * 3
var scoreEasy = 0 //will normally be zero (used for debugging)
var scoreMedium = 10000
var scoreHard = 50000
var scoreSuper = 100000
